"""add billing_url to vendors

Revision ID: 541e0c624065
Revises: e5b59e940b08
Create Date: 2026-05-25 17:30:32.527466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541e0c624065'
down_revision = 'e5b59e940b08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('billing_url')

    # ### end Alembic commands ###
