"""complete data model

Revision ID: e5b59e940b08
Revises: 
Create Date: 2026-05-25 16:37:30.142448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5b59e940b08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('gst_registration_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('rba_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rate_date', 'currency_code', name='uq_rba_rate_date_currency')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('api_available', sa.Boolean(), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('charges_gst', sa.Boolean(), nullable=False),
    sa.Column('ato_category', sa.String(length=100), nullable=False),
    sa.Column('sync_frequency', sa.String(length=20), nullable=False),
    sa.Column('pdf_required', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('financial_year_id', sa.Integer(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('amount_original', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('rba_rate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('amount_aud', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ato_category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('pdf_data', sa.LargeBinary(), nullable=True),
    sa.Column('invoice_attached', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('api_sync', 'pdf_upload', 'manual', name='expensesource'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    op.drop_table('vendors')
    op.drop_table('users')
    op.drop_table('rba_rates')
    op.drop_table('financial_years')
    op.drop_table('documents')
    # ### end Alembic commands ###
